# Generated by Django 2.2.7 on 2019-12-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_url',
            field=models.TextField(blank=True),
        ),
    ]
